# ETJump Release Pipeline
# Builds Windows and Linux binaries using gcc

trigger: none
pr: none

jobs:

- job: build_linux

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install gcc gcc-multilib g++-multilib mingw-w64
    displayName: 'Install Linux deps'

  - script: |
      sudo update-alternatives --set i686-w64-mingw32-gcc /usr/bin/i686-w64-mingw32-gcc-posix
      sudo update-alternatives --set i686-w64-mingw32-g++ /usr/bin/i686-w64-mingw32-g++-posix
      sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
      sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
      mkdir build && cd build
      sudo chmod +x ../scripts/build-release.sh
      ../scripts/build-release.sh -mingw
    displayName: 'Build release'

  - task: CopyFiles@2
    displayName: 'Copy artifact'
    inputs:
      contents: 'build/*.zip'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: ReleaseArchive
