name: etjump-CD

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux-x86_64:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Archive Linux artifacts
      uses: actions/upload-artifact@v2
      with:
        name: etjump-artifacts-linux-x86_64
        path: |
          etjump