name: ETJump CI

on:
  push:
    branches: [master, dev]
    tags-ignore:
      - "*"
    paths-ignore: &paths_ignore
      - docs/**
      - .editorconfig
      - .gitignore
      - .gitattributes
      - .clang-format
      - .clang-tidy
      - README.md
      - AGENTS.md
      - VERSION.txt
      - scripts/release.sh

  pull_request:
    branches: [master, dev]
    paths-ignore: *paths_ignore

  merge_group:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
