name: ETJump Release

on:
  workflow_dispatch:

  push:
    tags:
      - "*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  package:
    name: Package
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: etjump-artifacts-*
          merge-multiple: true
          path: ${{ github.workspace }}/build/etjump

      - name: Pack release zip
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
          make mod_release

      - name: Upload release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ETJump ${{ github.ref_name }}
          files: ${{ github.workspace }}/build/*.zip
          draft: true
